language: python
dist: trusty
python:
  - "2.7"
  - "3.5"
addons:
  firefox: 47.0.1
  apt:
    packages:
      - awesome
before_script:
  - pip uninstall -y pytest
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1
  - mkdir -p ~/.config/awesome
  - echo "require('awful'); tags = {}; tags[1] = awful.tag({'name'})" > ~/.config/awesome/rc.lua
  - "awesome &"
script: python setup.py test
