environment:
  matrix:
    - PYTHON: "C:\\Python27-x64"
      TOXENV: "chrome"
    - PYTHON: "C:\\Python35-x64"
      TOXENV: "chrome"
    - PYTHON: "C:\\Python27-x64"
      TOXENV: "ie"
    - PYTHON: "C:\\Python35-x64"
      TOXENV: "ie"
    - PYTHON: "C:\\Python27-x64"
      TOXENV: "marionette"
    - PYTHON: "C:\\Python35-x64"
      TOXENV: "marionette"

install:
  # Registry hack so driver can maintain connection
  - REG ADD "HKLM\SOFTWARE\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE" /v iexplore.exe /t REG_DWORD /d 00000000
  - REG ADD "HKLM\SOFTWARE\Wow6432Node\Microsoft\Internet Explorer\MAIN\FeatureControl\FEATURE_BFCACHE" /v iexplore.exe /t REG_DWORD /d 00000000
  - "%PYTHON%\\python.exe -m pip install tox"

before_test:
  - chromedriver.exe --version
  - geckodriver.exe --version
  - IEDriverServer.exe --version

build: off

test_script:
  - "%PYTHON%\\python.exe -m tox"
